- name: instalar kibana fedora
  include: elasticsearch-fedora.yml
  when: ansible_distribution == "Fedora" or ansible_distribution == "CentOS"

- name: iniciamos y habilitamos el servicio httpd
  service: name=elasticsearch state=started enabled=true
